# Generated by Django 5.2.8 on 2025-11-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
