# Generated by Django 5.2.8 on 2025-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_exam_subject_studentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='score',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='performance_level',
            field=models.IntegerField(choices=[(7, '7 - Exceeding Expectations'), (6, '6 - Above Expectations'), (5, '5 - Meeting Expectations'), (4, '4 - Approaching Expectations'), (3, '3 - Below Expectations'), (2, '2 - Emerging'), (1, '1 - Needs Support')], default=4),
        ),
    ]
