# Generated by Django 5.2.8 on 2025-12-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_studentresult_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='exam',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('Assignment', 'Assignment/Notes'), ('Video', 'Video Link'), ('Newsletter', 'School Communication')], default='Assignment', max_length=20),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='video_link',
            field=models.URLField(blank=True, help_text='Paste YouTube link here', null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_name',
            field=models.CharField(default='Term 1 2024', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_type',
            field=models.CharField(choices=[('Opener', 'Opener Exam'), ('Midterm', 'Midterm Exam'), ('Endterm', 'End of Term Exam')], default='Midterm', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='grade_class',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='performance_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('teacher_comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
